### ISSUE TITLE
project integration

### ISSUE THREAD

**Issue by giudig** [sysadmama/icinga2-notification-telegram#6]
Hi sysadmama, 

I found your commands very useful.
I would like to point out that I have included them in our git repo [_neteye4_ ](https://github.com/zampat/neteye4/tree/master/monitoring/notification/telegram
) with a basket for Icinga Director for the automatic creation of commands.

Kind Regards,

Giuseppe

**Comment by netzwerkgoettin** [comment]
Hi Guiseppe,

thank you for this information.
Please don't remove me as the initial creator :)

Cheers,
  Marianne
